before_install:
  - curl -sf https://test.docker.com | sh
  - docker --version

dist: bionic

language: bash

env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
  matrix:
    - VARIANT=alpine
    - VARIANT=debian

stages:
  - name: push
    if: tag IS present OR branch = master

script:
  - echo "$DOCKER_PASSWORD" | docker login -u nunofgs --password-stdin
  - docker run --privileged linuxkit/binfmt:v0.7
  - docker buildx create --use
  - docker buildx build --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 --build-arg "version=$TRAVIS_BRANCH" -t nunofgs/test:latest -f "$VARIANT/Dockerfile" --push .
