before_install:
  - curl -sf https://test.docker.com | sh
  # - sudo apt-get install docker-ce=18.02.0~ce-0~ubuntu
  - mkdir ~/.docker && echo '{ "experimental":"enabled" }' > ~/.docker/config.json
  - docker --version

dist: xenial

language: bash

env:
  matrix:
    - VARIANT=alpine
    - VARIANT=debian

stages:
  - name: push
    if: tag IS present OR branch = master

script:
  - docker login -u=nunofgs -p="$DOCKER_PASSWORD"
  - docker buildx create --use
  - docker buildx build --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 --build-arg "version=$TRAVIS_BRANCH" -t nunofgs/test:latest -f "$VARIANT/Dockerfile" .
